inp = list()
inp.append('a')
inp.append('b')
# print(inp.pop())
print(inp.count('a'))
inp.sort(reverse=True)
print(inp)
inp.reverse()
print(inp)
tempList = inp.copy()
inp.insert(1,'c')
inp.remove()
# inp.clear()
